on:
    workflow_dispatch: # allows us to trigger this workflow manually from the GitHub UI or via cli

jobs: 
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy application
              run: echo "deploying application"