on:
  push:
    branches:
      - main
      - "release/**"

    paths:
      - "src/**"
      - "test/**"
      - "package.json"
    
  pull_request:

    branches:
      - main
      - "release/**"

jobs:
  test: # name of the job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2

      - name: run tests # run test say hello function 
        run: uv run python -m pytest .
