on:
    schedule:
        - cron: '0 0 * * *' 
        - cron: '0 12 * * *'
    
jobs:
    daily-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Print a message
              run: echo "Running daily tests at $(date)"
             